// Schedule table for the mesh test bench (tb_schedule).
// Source: schedules/schedule_row.sched
// grid 3x3, frame 16 cycles, 19 rows, 72 alternatives
// Regenerate: python3 -m routing export-sv <schedule.sched> -o rtl/test/schedule_data.svh
// Node/dest values are 0-based SV mesh indices (schedule labels - 1);
// routes are zero-padded with LOCAL to 4 fields (router_pkg HEADER=12).
// Each 'array' is a constant function (iverilog cannot elaborate
// unpacked-array localparam literals); index i -> value i, as in
// the source schedule.
package tb_schedule_pkg;
  import router_pkg::*;

  localparam int SCHED_GRID = 3;
  localparam int SCHED_FRAME = 16;
  localparam int SCHED_ROWS = 19;
  localparam int SCHED_ALTS = 72;
  localparam int SCHED_MAX_ALTS = 8;
  localparam int SCHED_MAX_CLOCK = 12;

  function automatic int SCHED_ROW_NODE(input int i);
    case (i)
      0: SCHED_ROW_NODE = 0;
      1: SCHED_ROW_NODE = 0;
      2: SCHED_ROW_NODE = 1;
      3: SCHED_ROW_NODE = 1;
      4: SCHED_ROW_NODE = 2;
      5: SCHED_ROW_NODE = 2;
      6: SCHED_ROW_NODE = 3;
      7: SCHED_ROW_NODE = 3;
      8: SCHED_ROW_NODE = 3;
      9: SCHED_ROW_NODE = 4;
      10: SCHED_ROW_NODE = 5;
      11: SCHED_ROW_NODE = 5;
      12: SCHED_ROW_NODE = 6;
      13: SCHED_ROW_NODE = 6;
      14: SCHED_ROW_NODE = 6;
      15: SCHED_ROW_NODE = 7;
      16: SCHED_ROW_NODE = 7;
      17: SCHED_ROW_NODE = 8;
      18: SCHED_ROW_NODE = 8;
      default: SCHED_ROW_NODE = -1;
    endcase
  endfunction

  function automatic int SCHED_ROW_CLOCK(input int i);
    case (i)
      0: SCHED_ROW_CLOCK = 0;
      1: SCHED_ROW_CLOCK = 12;
      2: SCHED_ROW_CLOCK = 0;
      3: SCHED_ROW_CLOCK = 4;
      4: SCHED_ROW_CLOCK = 0;
      5: SCHED_ROW_CLOCK = 5;
      6: SCHED_ROW_CLOCK = 0;
      7: SCHED_ROW_CLOCK = 5;
      8: SCHED_ROW_CLOCK = 9;
      9: SCHED_ROW_CLOCK = 9;
      10: SCHED_ROW_CLOCK = 0;
      11: SCHED_ROW_CLOCK = 5;
      12: SCHED_ROW_CLOCK = 0;
      13: SCHED_ROW_CLOCK = 5;
      14: SCHED_ROW_CLOCK = 8;
      15: SCHED_ROW_CLOCK = 0;
      16: SCHED_ROW_CLOCK = 5;
      17: SCHED_ROW_CLOCK = 0;
      18: SCHED_ROW_CLOCK = 5;
      default: SCHED_ROW_CLOCK = -1;
    endcase
  endfunction

  function automatic int SCHED_ROW_ALT0(input int i);
    case (i)
      0: SCHED_ROW_ALT0 = 0;
      1: SCHED_ROW_ALT0 = 5;
      2: SCHED_ROW_ALT0 = 8;
      3: SCHED_ROW_ALT0 = 14;
      4: SCHED_ROW_ALT0 = 16;
      5: SCHED_ROW_ALT0 = 23;
      6: SCHED_ROW_ALT0 = 24;
      7: SCHED_ROW_ALT0 = 25;
      8: SCHED_ROW_ALT0 = 31;
      9: SCHED_ROW_ALT0 = 32;
      10: SCHED_ROW_ALT0 = 40;
      11: SCHED_ROW_ALT0 = 43;
      12: SCHED_ROW_ALT0 = 48;
      13: SCHED_ROW_ALT0 = 52;
      14: SCHED_ROW_ALT0 = 55;
      15: SCHED_ROW_ALT0 = 56;
      16: SCHED_ROW_ALT0 = 63;
      17: SCHED_ROW_ALT0 = 64;
      18: SCHED_ROW_ALT0 = 66;
      default: SCHED_ROW_ALT0 = -1;
    endcase
  endfunction

  function automatic int SCHED_ROW_NALT(input int i);
    case (i)
      0: SCHED_ROW_NALT = 5;
      1: SCHED_ROW_NALT = 3;
      2: SCHED_ROW_NALT = 6;
      3: SCHED_ROW_NALT = 2;
      4: SCHED_ROW_NALT = 7;
      5: SCHED_ROW_NALT = 1;
      6: SCHED_ROW_NALT = 1;
      7: SCHED_ROW_NALT = 6;
      8: SCHED_ROW_NALT = 1;
      9: SCHED_ROW_NALT = 8;
      10: SCHED_ROW_NALT = 3;
      11: SCHED_ROW_NALT = 5;
      12: SCHED_ROW_NALT = 4;
      13: SCHED_ROW_NALT = 3;
      14: SCHED_ROW_NALT = 1;
      15: SCHED_ROW_NALT = 7;
      16: SCHED_ROW_NALT = 1;
      17: SCHED_ROW_NALT = 2;
      18: SCHED_ROW_NALT = 6;
      default: SCHED_ROW_NALT = -1;
    endcase
  endfunction

  function automatic int SCHED_ALT_DST(input int i);
    case (i)
      0: SCHED_ALT_DST = 8;
      1: SCHED_ALT_DST = 5;
      2: SCHED_ALT_DST = 2;
      3: SCHED_ALT_DST = 4;
      4: SCHED_ALT_DST = 1;
      5: SCHED_ALT_DST = 7;
      6: SCHED_ALT_DST = 6;
      7: SCHED_ALT_DST = 3;
      8: SCHED_ALT_DST = 8;
      9: SCHED_ALT_DST = 5;
      10: SCHED_ALT_DST = 3;
      11: SCHED_ALT_DST = 7;
      12: SCHED_ALT_DST = 4;
      13: SCHED_ALT_DST = 2;
      14: SCHED_ALT_DST = 6;
      15: SCHED_ALT_DST = 0;
      16: SCHED_ALT_DST = 6;
      17: SCHED_ALT_DST = 3;
      18: SCHED_ALT_DST = 7;
      19: SCHED_ALT_DST = 0;
      20: SCHED_ALT_DST = 4;
      21: SCHED_ALT_DST = 8;
      22: SCHED_ALT_DST = 5;
      23: SCHED_ALT_DST = 1;
      24: SCHED_ALT_DST = 0;
      25: SCHED_ALT_DST = 8;
      26: SCHED_ALT_DST = 5;
      27: SCHED_ALT_DST = 7;
      28: SCHED_ALT_DST = 1;
      29: SCHED_ALT_DST = 6;
      30: SCHED_ALT_DST = 4;
      31: SCHED_ALT_DST = 2;
      32: SCHED_ALT_DST = 8;
      33: SCHED_ALT_DST = 0;
      34: SCHED_ALT_DST = 6;
      35: SCHED_ALT_DST = 2;
      36: SCHED_ALT_DST = 3;
      37: SCHED_ALT_DST = 5;
      38: SCHED_ALT_DST = 7;
      39: SCHED_ALT_DST = 1;
      40: SCHED_ALT_DST = 6;
      41: SCHED_ALT_DST = 7;
      42: SCHED_ALT_DST = 8;
      43: SCHED_ALT_DST = 0;
      44: SCHED_ALT_DST = 3;
      45: SCHED_ALT_DST = 1;
      46: SCHED_ALT_DST = 4;
      47: SCHED_ALT_DST = 2;
      48: SCHED_ALT_DST = 2;
      49: SCHED_ALT_DST = 1;
      50: SCHED_ALT_DST = 0;
      51: SCHED_ALT_DST = 3;
      52: SCHED_ALT_DST = 5;
      53: SCHED_ALT_DST = 8;
      54: SCHED_ALT_DST = 7;
      55: SCHED_ALT_DST = 4;
      56: SCHED_ALT_DST = 2;
      57: SCHED_ALT_DST = 0;
      58: SCHED_ALT_DST = 3;
      59: SCHED_ALT_DST = 5;
      60: SCHED_ALT_DST = 1;
      61: SCHED_ALT_DST = 6;
      62: SCHED_ALT_DST = 4;
      63: SCHED_ALT_DST = 8;
      64: SCHED_ALT_DST = 6;
      65: SCHED_ALT_DST = 7;
      66: SCHED_ALT_DST = 0;
      67: SCHED_ALT_DST = 3;
      68: SCHED_ALT_DST = 1;
      69: SCHED_ALT_DST = 2;
      70: SCHED_ALT_DST = 4;
      71: SCHED_ALT_DST = 5;
      default: SCHED_ALT_DST = -1;
    endcase
  endfunction

  function automatic int SCHED_ALT_HOPS(input int i);
    case (i)
      0: SCHED_ALT_HOPS = 4;
      1: SCHED_ALT_HOPS = 3;
      2: SCHED_ALT_HOPS = 2;
      3: SCHED_ALT_HOPS = 4;
      4: SCHED_ALT_HOPS = 1;
      5: SCHED_ALT_HOPS = 3;
      6: SCHED_ALT_HOPS = 2;
      7: SCHED_ALT_HOPS = 1;
      8: SCHED_ALT_HOPS = 3;
      9: SCHED_ALT_HOPS = 2;
      10: SCHED_ALT_HOPS = 4;
      11: SCHED_ALT_HOPS = 4;
      12: SCHED_ALT_HOPS = 3;
      13: SCHED_ALT_HOPS = 1;
      14: SCHED_ALT_HOPS = 3;
      15: SCHED_ALT_HOPS = 1;
      16: SCHED_ALT_HOPS = 4;
      17: SCHED_ALT_HOPS = 3;
      18: SCHED_ALT_HOPS = 3;
      19: SCHED_ALT_HOPS = 4;
      20: SCHED_ALT_HOPS = 2;
      21: SCHED_ALT_HOPS = 2;
      22: SCHED_ALT_HOPS = 1;
      23: SCHED_ALT_HOPS = 1;
      24: SCHED_ALT_HOPS = 1;
      25: SCHED_ALT_HOPS = 3;
      26: SCHED_ALT_HOPS = 4;
      27: SCHED_ALT_HOPS = 2;
      28: SCHED_ALT_HOPS = 4;
      29: SCHED_ALT_HOPS = 1;
      30: SCHED_ALT_HOPS = 3;
      31: SCHED_ALT_HOPS = 3;
      32: SCHED_ALT_HOPS = 2;
      33: SCHED_ALT_HOPS = 2;
      34: SCHED_ALT_HOPS = 2;
      35: SCHED_ALT_HOPS = 2;
      36: SCHED_ALT_HOPS = 1;
      37: SCHED_ALT_HOPS = 1;
      38: SCHED_ALT_HOPS = 3;
      39: SCHED_ALT_HOPS = 1;
      40: SCHED_ALT_HOPS = 3;
      41: SCHED_ALT_HOPS = 2;
      42: SCHED_ALT_HOPS = 1;
      43: SCHED_ALT_HOPS = 3;
      44: SCHED_ALT_HOPS = 2;
      45: SCHED_ALT_HOPS = 2;
      46: SCHED_ALT_HOPS = 1;
      47: SCHED_ALT_HOPS = 1;
      48: SCHED_ALT_HOPS = 4;
      49: SCHED_ALT_HOPS = 3;
      50: SCHED_ALT_HOPS = 2;
      51: SCHED_ALT_HOPS = 1;
      52: SCHED_ALT_HOPS = 3;
      53: SCHED_ALT_HOPS = 2;
      54: SCHED_ALT_HOPS = 1;
      55: SCHED_ALT_HOPS = 2;
      56: SCHED_ALT_HOPS = 3;
      57: SCHED_ALT_HOPS = 3;
      58: SCHED_ALT_HOPS = 2;
      59: SCHED_ALT_HOPS = 4;
      60: SCHED_ALT_HOPS = 2;
      61: SCHED_ALT_HOPS = 1;
      62: SCHED_ALT_HOPS = 1;
      63: SCHED_ALT_HOPS = 1;
      64: SCHED_ALT_HOPS = 2;
      65: SCHED_ALT_HOPS = 1;
      66: SCHED_ALT_HOPS = 4;
      67: SCHED_ALT_HOPS = 3;
      68: SCHED_ALT_HOPS = 3;
      69: SCHED_ALT_HOPS = 2;
      70: SCHED_ALT_HOPS = 2;
      71: SCHED_ALT_HOPS = 1;
      default: SCHED_ALT_HOPS = -1;
    endcase
  endfunction

  function automatic direction_e SCHED_ALT_D1(input int i);
    case (i)
      0: SCHED_ALT_D1 = EAST;
      1: SCHED_ALT_D1 = EAST;
      2: SCHED_ALT_D1 = EAST;
      3: SCHED_ALT_D1 = EAST;
      4: SCHED_ALT_D1 = EAST;
      5: SCHED_ALT_D1 = EAST;
      6: SCHED_ALT_D1 = SOUTH;
      7: SCHED_ALT_D1 = SOUTH;
      8: SCHED_ALT_D1 = EAST;
      9: SCHED_ALT_D1 = EAST;
      10: SCHED_ALT_D1 = EAST;
      11: SCHED_ALT_D1 = EAST;
      12: SCHED_ALT_D1 = EAST;
      13: SCHED_ALT_D1 = EAST;
      14: SCHED_ALT_D1 = SOUTH;
      15: SCHED_ALT_D1 = WEST;
      16: SCHED_ALT_D1 = SOUTH;
      17: SCHED_ALT_D1 = SOUTH;
      18: SCHED_ALT_D1 = SOUTH;
      19: SCHED_ALT_D1 = SOUTH;
      20: SCHED_ALT_D1 = SOUTH;
      21: SCHED_ALT_D1 = SOUTH;
      22: SCHED_ALT_D1 = SOUTH;
      23: SCHED_ALT_D1 = WEST;
      24: SCHED_ALT_D1 = NORTH;
      25: SCHED_ALT_D1 = SOUTH;
      26: SCHED_ALT_D1 = SOUTH;
      27: SCHED_ALT_D1 = SOUTH;
      28: SCHED_ALT_D1 = SOUTH;
      29: SCHED_ALT_D1 = SOUTH;
      30: SCHED_ALT_D1 = SOUTH;
      31: SCHED_ALT_D1 = NORTH;
      32: SCHED_ALT_D1 = EAST;
      33: SCHED_ALT_D1 = WEST;
      34: SCHED_ALT_D1 = WEST;
      35: SCHED_ALT_D1 = NORTH;
      36: SCHED_ALT_D1 = WEST;
      37: SCHED_ALT_D1 = EAST;
      38: SCHED_ALT_D1 = WEST;
      39: SCHED_ALT_D1 = NORTH;
      40: SCHED_ALT_D1 = SOUTH;
      41: SCHED_ALT_D1 = SOUTH;
      42: SCHED_ALT_D1 = SOUTH;
      43: SCHED_ALT_D1 = WEST;
      44: SCHED_ALT_D1 = WEST;
      45: SCHED_ALT_D1 = NORTH;
      46: SCHED_ALT_D1 = WEST;
      47: SCHED_ALT_D1 = NORTH;
      48: SCHED_ALT_D1 = NORTH;
      49: SCHED_ALT_D1 = NORTH;
      50: SCHED_ALT_D1 = NORTH;
      51: SCHED_ALT_D1 = NORTH;
      52: SCHED_ALT_D1 = EAST;
      53: SCHED_ALT_D1 = EAST;
      54: SCHED_ALT_D1 = EAST;
      55: SCHED_ALT_D1 = EAST;
      56: SCHED_ALT_D1 = NORTH;
      57: SCHED_ALT_D1 = NORTH;
      58: SCHED_ALT_D1 = WEST;
      59: SCHED_ALT_D1 = NORTH;
      60: SCHED_ALT_D1 = NORTH;
      61: SCHED_ALT_D1 = WEST;
      62: SCHED_ALT_D1 = NORTH;
      63: SCHED_ALT_D1 = EAST;
      64: SCHED_ALT_D1 = WEST;
      65: SCHED_ALT_D1 = WEST;
      66: SCHED_ALT_D1 = NORTH;
      67: SCHED_ALT_D1 = NORTH;
      68: SCHED_ALT_D1 = NORTH;
      69: SCHED_ALT_D1 = NORTH;
      70: SCHED_ALT_D1 = NORTH;
      71: SCHED_ALT_D1 = NORTH;
      default: SCHED_ALT_D1 = LOCAL;
    endcase
  endfunction

  function automatic direction_e SCHED_ALT_D2(input int i);
    case (i)
      0: SCHED_ALT_D2 = EAST;
      1: SCHED_ALT_D2 = EAST;
      2: SCHED_ALT_D2 = EAST;
      3: SCHED_ALT_D2 = EAST;
      4: SCHED_ALT_D2 = LOCAL;
      5: SCHED_ALT_D2 = SOUTH;
      6: SCHED_ALT_D2 = SOUTH;
      7: SCHED_ALT_D2 = LOCAL;
      8: SCHED_ALT_D2 = SOUTH;
      9: SCHED_ALT_D2 = SOUTH;
      10: SCHED_ALT_D2 = SOUTH;
      11: SCHED_ALT_D2 = SOUTH;
      12: SCHED_ALT_D2 = SOUTH;
      13: SCHED_ALT_D2 = LOCAL;
      14: SCHED_ALT_D2 = WEST;
      15: SCHED_ALT_D2 = LOCAL;
      16: SCHED_ALT_D2 = WEST;
      17: SCHED_ALT_D2 = WEST;
      18: SCHED_ALT_D2 = SOUTH;
      19: SCHED_ALT_D2 = WEST;
      20: SCHED_ALT_D2 = WEST;
      21: SCHED_ALT_D2 = SOUTH;
      22: SCHED_ALT_D2 = LOCAL;
      23: SCHED_ALT_D2 = LOCAL;
      24: SCHED_ALT_D2 = LOCAL;
      25: SCHED_ALT_D2 = EAST;
      26: SCHED_ALT_D2 = EAST;
      27: SCHED_ALT_D2 = EAST;
      28: SCHED_ALT_D2 = EAST;
      29: SCHED_ALT_D2 = LOCAL;
      30: SCHED_ALT_D2 = EAST;
      31: SCHED_ALT_D2 = EAST;
      32: SCHED_ALT_D2 = SOUTH;
      33: SCHED_ALT_D2 = NORTH;
      34: SCHED_ALT_D2 = SOUTH;
      35: SCHED_ALT_D2 = EAST;
      36: SCHED_ALT_D2 = LOCAL;
      37: SCHED_ALT_D2 = LOCAL;
      38: SCHED_ALT_D2 = SOUTH;
      39: SCHED_ALT_D2 = LOCAL;
      40: SCHED_ALT_D2 = WEST;
      41: SCHED_ALT_D2 = WEST;
      42: SCHED_ALT_D2 = LOCAL;
      43: SCHED_ALT_D2 = NORTH;
      44: SCHED_ALT_D2 = WEST;
      45: SCHED_ALT_D2 = WEST;
      46: SCHED_ALT_D2 = LOCAL;
      47: SCHED_ALT_D2 = LOCAL;
      48: SCHED_ALT_D2 = NORTH;
      49: SCHED_ALT_D2 = NORTH;
      50: SCHED_ALT_D2 = NORTH;
      51: SCHED_ALT_D2 = LOCAL;
      52: SCHED_ALT_D2 = EAST;
      53: SCHED_ALT_D2 = EAST;
      54: SCHED_ALT_D2 = LOCAL;
      55: SCHED_ALT_D2 = NORTH;
      56: SCHED_ALT_D2 = NORTH;
      57: SCHED_ALT_D2 = WEST;
      58: SCHED_ALT_D2 = NORTH;
      59: SCHED_ALT_D2 = NORTH;
      60: SCHED_ALT_D2 = NORTH;
      61: SCHED_ALT_D2 = LOCAL;
      62: SCHED_ALT_D2 = LOCAL;
      63: SCHED_ALT_D2 = LOCAL;
      64: SCHED_ALT_D2 = WEST;
      65: SCHED_ALT_D2 = LOCAL;
      66: SCHED_ALT_D2 = WEST;
      67: SCHED_ALT_D2 = WEST;
      68: SCHED_ALT_D2 = WEST;
      69: SCHED_ALT_D2 = NORTH;
      70: SCHED_ALT_D2 = WEST;
      71: SCHED_ALT_D2 = LOCAL;
      default: SCHED_ALT_D2 = LOCAL;
    endcase
  endfunction

  function automatic direction_e SCHED_ALT_D3(input int i);
    case (i)
      0: SCHED_ALT_D3 = SOUTH;
      1: SCHED_ALT_D3 = SOUTH;
      2: SCHED_ALT_D3 = LOCAL;
      3: SCHED_ALT_D3 = SOUTH;
      4: SCHED_ALT_D3 = LOCAL;
      5: SCHED_ALT_D3 = SOUTH;
      6: SCHED_ALT_D3 = LOCAL;
      7: SCHED_ALT_D3 = LOCAL;
      8: SCHED_ALT_D3 = SOUTH;
      9: SCHED_ALT_D3 = LOCAL;
      10: SCHED_ALT_D3 = WEST;
      11: SCHED_ALT_D3 = WEST;
      12: SCHED_ALT_D3 = WEST;
      13: SCHED_ALT_D3 = LOCAL;
      14: SCHED_ALT_D3 = SOUTH;
      15: SCHED_ALT_D3 = LOCAL;
      16: SCHED_ALT_D3 = WEST;
      17: SCHED_ALT_D3 = WEST;
      18: SCHED_ALT_D3 = WEST;
      19: SCHED_ALT_D3 = WEST;
      20: SCHED_ALT_D3 = LOCAL;
      21: SCHED_ALT_D3 = LOCAL;
      22: SCHED_ALT_D3 = LOCAL;
      23: SCHED_ALT_D3 = LOCAL;
      24: SCHED_ALT_D3 = LOCAL;
      25: SCHED_ALT_D3 = EAST;
      26: SCHED_ALT_D3 = NORTH;
      27: SCHED_ALT_D3 = LOCAL;
      28: SCHED_ALT_D3 = NORTH;
      29: SCHED_ALT_D3 = LOCAL;
      30: SCHED_ALT_D3 = NORTH;
      31: SCHED_ALT_D3 = EAST;
      32: SCHED_ALT_D3 = LOCAL;
      33: SCHED_ALT_D3 = LOCAL;
      34: SCHED_ALT_D3 = LOCAL;
      35: SCHED_ALT_D3 = LOCAL;
      36: SCHED_ALT_D3 = LOCAL;
      37: SCHED_ALT_D3 = LOCAL;
      38: SCHED_ALT_D3 = EAST;
      39: SCHED_ALT_D3 = LOCAL;
      40: SCHED_ALT_D3 = WEST;
      41: SCHED_ALT_D3 = LOCAL;
      42: SCHED_ALT_D3 = LOCAL;
      43: SCHED_ALT_D3 = WEST;
      44: SCHED_ALT_D3 = LOCAL;
      45: SCHED_ALT_D3 = LOCAL;
      46: SCHED_ALT_D3 = LOCAL;
      47: SCHED_ALT_D3 = LOCAL;
      48: SCHED_ALT_D3 = EAST;
      49: SCHED_ALT_D3 = EAST;
      50: SCHED_ALT_D3 = LOCAL;
      51: SCHED_ALT_D3 = LOCAL;
      52: SCHED_ALT_D3 = NORTH;
      53: SCHED_ALT_D3 = LOCAL;
      54: SCHED_ALT_D3 = LOCAL;
      55: SCHED_ALT_D3 = LOCAL;
      56: SCHED_ALT_D3 = EAST;
      57: SCHED_ALT_D3 = NORTH;
      58: SCHED_ALT_D3 = LOCAL;
      59: SCHED_ALT_D3 = EAST;
      60: SCHED_ALT_D3 = LOCAL;
      61: SCHED_ALT_D3 = LOCAL;
      62: SCHED_ALT_D3 = LOCAL;
      63: SCHED_ALT_D3 = LOCAL;
      64: SCHED_ALT_D3 = LOCAL;
      65: SCHED_ALT_D3 = LOCAL;
      66: SCHED_ALT_D3 = NORTH;
      67: SCHED_ALT_D3 = WEST;
      68: SCHED_ALT_D3 = NORTH;
      69: SCHED_ALT_D3 = LOCAL;
      70: SCHED_ALT_D3 = LOCAL;
      71: SCHED_ALT_D3 = LOCAL;
      default: SCHED_ALT_D3 = LOCAL;
    endcase
  endfunction

  function automatic direction_e SCHED_ALT_D4(input int i);
    case (i)
      0: SCHED_ALT_D4 = SOUTH;
      1: SCHED_ALT_D4 = LOCAL;
      2: SCHED_ALT_D4 = LOCAL;
      3: SCHED_ALT_D4 = WEST;
      4: SCHED_ALT_D4 = LOCAL;
      5: SCHED_ALT_D4 = LOCAL;
      6: SCHED_ALT_D4 = LOCAL;
      7: SCHED_ALT_D4 = LOCAL;
      8: SCHED_ALT_D4 = LOCAL;
      9: SCHED_ALT_D4 = LOCAL;
      10: SCHED_ALT_D4 = WEST;
      11: SCHED_ALT_D4 = SOUTH;
      12: SCHED_ALT_D4 = LOCAL;
      13: SCHED_ALT_D4 = LOCAL;
      14: SCHED_ALT_D4 = LOCAL;
      15: SCHED_ALT_D4 = LOCAL;
      16: SCHED_ALT_D4 = SOUTH;
      17: SCHED_ALT_D4 = LOCAL;
      18: SCHED_ALT_D4 = LOCAL;
      19: SCHED_ALT_D4 = NORTH;
      20: SCHED_ALT_D4 = LOCAL;
      21: SCHED_ALT_D4 = LOCAL;
      22: SCHED_ALT_D4 = LOCAL;
      23: SCHED_ALT_D4 = LOCAL;
      24: SCHED_ALT_D4 = LOCAL;
      25: SCHED_ALT_D4 = LOCAL;
      26: SCHED_ALT_D4 = EAST;
      27: SCHED_ALT_D4 = LOCAL;
      28: SCHED_ALT_D4 = NORTH;
      29: SCHED_ALT_D4 = LOCAL;
      30: SCHED_ALT_D4 = LOCAL;
      31: SCHED_ALT_D4 = LOCAL;
      32: SCHED_ALT_D4 = LOCAL;
      33: SCHED_ALT_D4 = LOCAL;
      34: SCHED_ALT_D4 = LOCAL;
      35: SCHED_ALT_D4 = LOCAL;
      36: SCHED_ALT_D4 = LOCAL;
      37: SCHED_ALT_D4 = LOCAL;
      38: SCHED_ALT_D4 = LOCAL;
      39: SCHED_ALT_D4 = LOCAL;
      40: SCHED_ALT_D4 = LOCAL;
      41: SCHED_ALT_D4 = LOCAL;
      42: SCHED_ALT_D4 = LOCAL;
      43: SCHED_ALT_D4 = LOCAL;
      44: SCHED_ALT_D4 = LOCAL;
      45: SCHED_ALT_D4 = LOCAL;
      46: SCHED_ALT_D4 = LOCAL;
      47: SCHED_ALT_D4 = LOCAL;
      48: SCHED_ALT_D4 = EAST;
      49: SCHED_ALT_D4 = LOCAL;
      50: SCHED_ALT_D4 = LOCAL;
      51: SCHED_ALT_D4 = LOCAL;
      52: SCHED_ALT_D4 = LOCAL;
      53: SCHED_ALT_D4 = LOCAL;
      54: SCHED_ALT_D4 = LOCAL;
      55: SCHED_ALT_D4 = LOCAL;
      56: SCHED_ALT_D4 = LOCAL;
      57: SCHED_ALT_D4 = LOCAL;
      58: SCHED_ALT_D4 = LOCAL;
      59: SCHED_ALT_D4 = SOUTH;
      60: SCHED_ALT_D4 = LOCAL;
      61: SCHED_ALT_D4 = LOCAL;
      62: SCHED_ALT_D4 = LOCAL;
      63: SCHED_ALT_D4 = LOCAL;
      64: SCHED_ALT_D4 = LOCAL;
      65: SCHED_ALT_D4 = LOCAL;
      66: SCHED_ALT_D4 = WEST;
      67: SCHED_ALT_D4 = LOCAL;
      68: SCHED_ALT_D4 = LOCAL;
      69: SCHED_ALT_D4 = LOCAL;
      70: SCHED_ALT_D4 = LOCAL;
      71: SCHED_ALT_D4 = LOCAL;
      default: SCHED_ALT_D4 = LOCAL;
    endcase
  endfunction

endpackage
